import streamlit as st
st.set_page_config(page_title='Home',page_icon="🐶")


st.title("🎈 My new app")
breeds = dog_breeds = [
    "Affenpinscher",
    "Afghan Hound",
    "Aidi",
    "Airedale Terrier",
    "Akbash Dog",
    "Alapaha Blue Blood Bulldog",
    "Alaskan Malamute",
    "Alpine Dachsbracke",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Eskimo Dog",
    "American Foxhound",
    "American Pitbull Terrier",
    "American Staffordshire Terrier",
    "American Water Spaniel",
    "Anatolian Shepherd Dog",
    "Appenzeller Sennenhund",
    "Ardennes Cattle Dog",
    "Australian Cattle Dog",
    "Australian Dingo",
    "Australian Kelpie",
    "Australian Shepherd",
    "Australian Stumpy Tail Cattle Dog",
    "Australian Terrier",
    "Austrian Black and Tan Hound",
    "Austrian Shorthaired Pinscher",
    "Auvergne Pointer",
    "Azawakh",
    "Barbet",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bedlington Terrier",
    "Belgian Groenendael",
    "Belgian Laekenois",
    "Belgian Malinois",
    "Belgian Tervueren",
    "Bergamasco",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Billy",
    "Black and Tan Coonhound",
    "Black Russian Terrier",
    "Bloodhound",
    "Blue Picardy Spaniel",
    "Bolognese",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bourbonnais Pointer",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Briard",
    "Brittany Spaniel",
    "Brussels Griffon",
    "Bulldog",
    "Bullmastiff",
    "Bull Terrier",
    "Cairn Terrier",
    "Canaan Dog",
    "Cane Corso",
    "Cao de Agua Portugues",
    "Cão de Castro Laboreiro",
    "Cão de Fila de São Miguel",
    "Cardigan Welsh Corgi",
    "Catalonian Sheepdog",
    "Caucasian Ovtcharka",
    "Cesky Terrier",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested",
    "Chinese Sharpei",
    "Chinook",
    "Chow Chow",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Setter",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "Eurasier",
    "Field Spaniel",
    "Fila Brasiliero",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat Coated Retriever",
    "French Bulldog",
    "German Hunt Terrier",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "German Spitz",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Gotland Hound",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lhasa Apso",
    "Löwchen",
    "Maltese",
    "Manchester Terrier",
    "Miniature American Shepherd",
    "Miniature Bull Terrier",
    "Miniature Fox Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Mudi",
    "Neapolitan Mastiff",
    "New Guinea Singing Dog",
    "Newfoundland",
    "Norfolk Terrier",
    "Norrbottenspets"
]

dog_breed = st.selectbox('What is the breed of your dog',breeds )
st.write(
    "Let's start building! For help and inspiration, head over to [docs.streamlit.io](https://docs.streamlit.io/)."
)
